services:
  - type: web
    name: api-central-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 240 --workers 1 --threads 2 app:app
    autoDeploy: true
    envVars:
      - key: KICK_API_URL
        value: https://kick-duelo-api.onrender.com
      - key: WARZONE_API_URL
        value: https://warzone-api-qbn9.onrender.com
      - key: REDSEC_API_URL
        value: https://redsec-loadout-api.onrender.com
